/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFeedbackHost: typeof import('./src/components/AppFeedbackHost.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    AppSearchInput: typeof import('./src/components/AppSearchInput.vue')['default']
    FormStepCounter: typeof import('./src/components/FormStepCounter.vue')['default']
    GoodsCardSkeleton: typeof import('./src/components/GoodsCardSkeleton.vue')['default']
    GoodsImage: typeof import('./src/components/GoodsImage.vue')['default']
    GoodsNameTypeahead: typeof import('./src/components/GoodsNameTypeahead.vue')['default']
    GoodsNewListingBadge: typeof import('./src/components/GoodsNewListingBadge.vue')['default']
    GoodsPriceLabel: typeof import('./src/components/GoodsPriceLabel.vue')['default']
    GoodsSalesTagRow: typeof import('./src/components/GoodsSalesTagRow.vue')['default']
    GoodsSoldOutBadge: typeof import('./src/components/GoodsSoldOutBadge.vue')['default']
    NavBackIcon: typeof import('./src/components/NavBackIcon.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSkeleton: typeof import('@nutui/nutui-taro')['Skeleton']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    OrderListStatusTabs: typeof import('./src/components/OrderListStatusTabs.vue')['default']
    OrderStatusSteps: typeof import('./src/components/OrderStatusSteps.vue')['default']
    SmartAddressInput: typeof import('./src/components/SmartAddressInput.vue')['default']
    WikiAnswerCard: typeof import('./src/components/WikiAnswerCard.vue')['default']
    WikiAtlasSection: typeof import('./src/components/wiki/WikiAtlasSection.vue')['default']
    WikiCareSection: typeof import('./src/components/wiki/WikiCareSection.vue')['default']
    WikiDetailContent: typeof import('./src/components/wiki/WikiDetailContent.vue')['default']
    WikiDetailHero: typeof import('./src/components/wiki/WikiDetailHero.vue')['default']
    WikiEntryPanel: typeof import('./src/components/wiki/WikiEntryPanel.vue')['default']
    WikiFieldSlot: typeof import('./src/components/WikiFieldSlot.vue')['default']
    WikiLanguageSection: typeof import('./src/components/wiki/WikiLanguageSection.vue')['default']
  }
}
