const FLOWER_SEED = [
  {
    name: '玫瑰',
    icon: '🌹',
    sort: 100,
    defaultUnit: '支',
    description: '经典爱情花材，适合表白、纪念日与日常赠礼。',
    varieties: [
      { name: '红玫瑰', description: '色泽浓艳，象征热烈真挚的爱意。', sort: 100 },
      { name: '粉玫瑰', description: '温柔甜美，适合表达初恋与感谢。', sort: 95 },
      { name: '白玫瑰', description: '纯净素雅，寓意尊敬与纯粹的爱。', sort: 90 },
      { name: '香槟玫瑰', description: '低调优雅，适合告白与纪念日。', sort: 85 },
      { name: '卡罗拉', description: '花型饱满、耐开，花店常用经典红玫瑰品种。', sort: 80 },
      { name: '戴安娜', description: '粉色调玫瑰，花瓣层叠，适合温柔系花束。', sort: 75 },
      { name: '佛洛依德', description: '大花型玫红玫瑰，高级感强，适合精品花束。', sort: 70 },
      { name: '艾莎', description: '粉白镶边玫瑰，清新浪漫，适合少女风花束。', sort: 65 },
    ],
  },
  {
    name: '牡丹',
    icon: '🌺',
    sort: 95,
    defaultUnit: '支',
    description: '国色天香，花型雍容，适合高端礼盒与节庆赠礼。',
    varieties: [
      { name: '黄天霸', description: '金黄色重瓣牡丹，花王级别，大气华贵。', sort: 100 },
      { name: '洛阳红', description: '深红色传统牡丹，喜庆热烈，适合开业贺礼。', sort: 95 },
      { name: '魏紫', description: '淡紫色牡丹，典雅含蓄，适合长辈与雅集。', sort: 90 },
      { name: '赵粉', description: '粉色调牡丹，温婉柔美，适合春日主题花束。', sort: 85 },
      { name: '彤云', description: '红艳层叠，花量足，适合大型花艺作品。', sort: 80 },
    ],
  },
  {
    name: '百合',
    icon: '🤍',
    sort: 90,
    defaultUnit: '支',
    description: '香气清雅，寓意百年好合，适合婚礼与探望。',
    varieties: [
      { name: '白百合', description: '纯洁高雅，婚礼与探望常用。', sort: 100 },
      { name: '粉百合', description: '温柔浪漫，适合生日与纪念日。', sort: 95 },
      { name: '黄百合', description: '明亮温暖，寓意快乐与感激。', sort: 90 },
      { name: '香水百合', description: '香气浓郁，花型大，适合主花使用。', sort: 85 },
      { name: '西伯利亚百合', description: '白色单瓣百合，线条简洁，适合现代风花束。', sort: 80 },
    ],
  },
  {
    name: '康乃馨',
    icon: '💗',
    sort: 85,
    defaultUnit: '支',
    description: '母亲节、感恩与祝福的经典花材。',
    varieties: [
      { name: '红色康乃馨', description: '热烈感恩，适合母亲节与祝福。', sort: 100 },
      { name: '粉色康乃馨', description: '温馨甜美，适合送给母亲与长辈。', sort: 95 },
      { name: '白色康乃馨', description: '纯洁思念，适合悼念与怀念。', sort: 90 },
    ],
  },
  {
    name: '向日葵',
    icon: '🌻',
    sort: 80,
    defaultUnit: '支',
    description: '阳光积极，适合毕业、加油与日常治愈系花束。',
    varieties: [
      { name: '向日葵', description: '经典大花盘向日葵，明亮治愈。', sort: 100 },
      { name: '迷你向日葵', description: '小巧可爱，适合混搭与伴手花束。', sort: 90 },
    ],
  },
  {
    name: '郁金香',
    icon: '🌷',
    sort: 75,
    defaultUnit: '支',
    description: '线条优美，春日感强，适合精致小花束。',
    varieties: [
      { name: '红色郁金香', description: '热烈告白，适合情人节与纪念日。', sort: 100 },
      { name: '黄色郁金香', description: '明亮开朗，适合生日与朋友赠礼。', sort: 95 },
      { name: '粉色郁金香', description: '甜美浪漫，适合表白与约会。', sort: 90 },
      { name: '白色郁金香', description: '纯净简约，适合清新风格花束。', sort: 85 },
    ],
  },
  {
    name: '绣球',
    icon: '💠',
    sort: 70,
    defaultUnit: '支',
    description: '团状花型，适合韩式花束与婚礼布置。',
    varieties: [
      { name: '蓝色绣球', description: '清凉梦幻，适合夏日与婚礼主题。', sort: 100 },
      { name: '粉色绣球', description: '浪漫柔美，适合生日与家居插花。', sort: 95 },
      { name: '白色绣球', description: '纯净大气，适合婚礼与极简风花束。', sort: 90 },
    ],
  },
  {
    name: '洋桔梗',
    icon: '🪻',
    sort: 65,
    defaultUnit: '支',
    description: '轻盈灵动，百搭配花，也适合单品种小花束。',
    varieties: [
      { name: '白色洋桔梗', description: '清新百搭，适合混搭与新娘手捧。', sort: 100 },
      { name: '紫色洋桔梗', description: '浪漫优雅，适合法式花束。', sort: 95 },
      { name: '绿色洋桔梗', description: '自然清爽，适合森系与野趣花束。', sort: 90 },
    ],
  },
  {
    name: '满天星',
    icon: '✨',
    sort: 60,
    defaultUnit: '束',
    description: '轻盈点缀或整束售卖，适合干花与永生花。',
    varieties: [
      { name: '白色满天星', description: '经典满天星，适合配花与整束售卖。', sort: 100 },
      { name: '彩色满天星', description: '染色满天星，适合少女心与节日花束。', sort: 90 },
    ],
  },
  {
    name: '非洲菊',
    icon: '🌼',
    sort: 58,
    defaultUnit: '支',
    description: '色彩明亮，适合庆典花篮与混搭花束。',
    varieties: [
      { name: '红色非洲菊', description: '热烈明亮，适合庆典与祝福。', sort: 100 },
      { name: '黄色非洲菊', description: '阳光活力，适合开业与加油花束。', sort: 95 },
      { name: '粉色非洲菊', description: '温柔甜美，适合日常赠礼。', sort: 90 },
    ],
  },
  {
    name: '马蹄莲',
    icon: '🤍',
    sort: 56,
    defaultUnit: '支',
    description: '线条优雅，婚礼手捧与极简花艺常用。',
    varieties: [
      { name: '白色马蹄莲', description: '圣洁经典，婚礼常用。', sort: 100 },
      { name: '黄色马蹄莲', description: '明亮尊贵，适合高端礼盒。', sort: 95 },
      { name: '粉色马蹄莲', description: '温柔浪漫，适合新娘手捧。', sort: 90 },
    ],
  },
  {
    name: '芍药',
    icon: '🌸',
    sort: 54,
    defaultUnit: '支',
    description: '春日大花材，适合中式花束与婚礼。',
    varieties: [
      { name: '粉色芍药', description: '温柔层叠，春日表白常用。', sort: 100 },
      { name: '白色芍药', description: '纯洁优雅，婚礼与庆典适用。', sort: 95 },
      { name: '珊瑚芍药', description: '独特色调，适合精品花束。', sort: 90 },
    ],
  },
  {
    name: '菊花',
    icon: '🌼',
    sort: 52,
    defaultUnit: '支',
    description: '秋季应季，配花与祭奠场景常用。',
    varieties: [
      { name: '黄菊花', description: '经典秋菊，适合敬老与日常配花。', sort: 100 },
      { name: '白菊花', description: '素雅洁净，祭奠与探望常用。', sort: 95 },
      { name: '乒乓菊', description: '球形花头，适合混搭与礼盒。', sort: 90 },
    ],
  },
  {
    name: '勿忘我',
    icon: '💙',
    sort: 50,
    defaultUnit: '支',
    description: '小花配材，表达记忆与思念。',
    varieties: [
      { name: '蓝色勿忘我', description: '经典蓝色，寓意永恒记忆。', sort: 100 },
      { name: '粉色勿忘我', description: '浪漫甜蜜，适合表白配花。', sort: 95 },
    ],
  },
  {
    name: '紫罗兰',
    icon: '💜',
    sort: 48,
    defaultUnit: '支',
    description: '香气幽雅，适合春季小束与混搭。',
    varieties: [
      { name: '紫色紫罗兰', description: '经典紫色，香气淡雅。', sort: 100 },
      { name: '白色紫罗兰', description: '纯洁清香，适合精致小束。', sort: 95 },
    ],
  },
  {
    name: '风信子',
    icon: '🔔',
    sort: 46,
    defaultUnit: '支',
    description: '春季球根，香气浓郁，节日家居常用。',
    varieties: [
      { name: '蓝色风信子', description: '经典蓝色，寓意生命与恒心。', sort: 100 },
      { name: '粉色风信子', description: '浪漫甜美，适合春日赠礼。', sort: 95 },
      { name: '白色风信子', description: '纯洁清香，适合家居插花。', sort: 90 },
    ],
  },
  {
    name: '蝴蝶兰',
    icon: '🦋',
    sort: 44,
    defaultUnit: '盆',
    description: '高端礼品兰，花期长，适合开业贺礼。',
    varieties: [
      { name: '白色蝴蝶兰', description: '纯洁祝福，商务与贺礼常用。', sort: 100 },
      { name: '粉色蝴蝶兰', description: '幸福浪漫，适合生日与纪念日。', sort: 95 },
      { name: '黄色蝴蝶兰', description: '吉祥富贵，适合开业贺礼。', sort: 90 },
    ],
  },
  {
    name: '洋牡丹',
    icon: '🌺',
    sort: 42,
    defaultUnit: '支',
    description: '层叠花型，春季法式花束热门花材。',
    varieties: [
      { name: '粉色洋牡丹', description: '温柔层叠，新娘手捧常用。', sort: 100 },
      { name: '白色洋牡丹', description: '纯净优雅，法式花束适用。', sort: 95 },
      { name: '橙色洋牡丹', description: '活力明亮，适合春日混搭。', sort: 90 },
    ],
  },
]

module.exports = { FLOWER_SEED }
