const { exportKind } = require('./shared')

function spec(variety, alias, extra) {
  return { variety, alias, ...extra }
}

const CHRYS = [
  spec('乒乓菊', 'Ping Pong', {
    scientificName: "Chrysanthemum 'Ping Pong'",
    namingNote: '球形小菊，圆润可爱，配花与家居高频',
    color: '多色，球形轮廓，花瓣紧密排列如小球',
    scent: '几乎无香',
    featureRefs: ['trait.spray_ball'],
    distinguishFrom: [
      { name: '非洲菊', difference: '扁盘花型，而非球形' },
      { name: '小雏菊', difference: '扁瓣，而非球状' },
    ],
    meaning: '可爱、治愈与「圆滚滚的小快乐」',
    paragraphs: [
      '乒乓菊像把很多小圆球串在枝上——适合送朋友、做家居点缀、或需要「可爱而不是隆重」的菊类场景。',
      '耐插，勤换水即可；与尤加利、满天星同插，整束会更轻、更甜。',
    ],
    occasions: ['送朋友', '家居', '配花', '生日'],
    colorLabel: '多色',
    colorMeaning: '可爱、治愈',
    pairing: [{ style: '可爱', flowers: ['满天星', '尤加利叶'], note: '多色轻' }],
    caution: '保持水质清洁；避免挤压球状花头。',
    careSummary: '乒乓菊球形小菊；勤换水，轻拿轻放，保持通风。',
    careTips: ['勤换水', '避免挤压'],
    bloomNote: '球形小菊，耐插 10—14 天',
  }),
  spec('小雏菊', 'Daisy', {
    scientificName: "Chrysanthemum 'Daisy'",
    namingNote: '扁瓣小菊，野趣自然风代表',
    color: '白或粉，扁瓣，中心明显，整体轻盈',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white'],
    meaning: '清新、野趣与「很轻的一束白」',
    paragraphs: [
      '小雏菊是野趣花束的「气氛组」——与蕾丝花、尤加利、郁金香同插，立刻有田园感。',
      '耐插、易养，适合日常家居；婚礼自然风也常用。',
    ],
    occasions: ['自然风', '婚礼', '日常家居'],
    colorLabel: '白/粉',
    colorMeaning: '清新、野趣',
    pairing: [{ style: '野趣', flowers: ['蕾丝花', '尤加利叶'], note: '白绿' }],
    caution: '勤换水；避免花瓣沾水。',
    careSummary: '小雏菊扁瓣轻盈；勤换水，保持通风。',
    careTips: ['勤换水'],
    bloomNote: '野趣小菊，耐插',
  }),
  spec('洋甘菊', 'Chamomile', {
    scientificName: "Chrysanthemum 'Chamomile'",
    namingNote: '迷你扁瓣菊，森系与配花常用',
    color: '白心黄芯，瓣细，整体迷你',
    scent: '淡草香',
    featureRefs: ['trait.pure_white'],
    meaning: '治愈、森系与「像小太阳的白」',
    paragraphs: [
      '洋甘菊适合森系、法式混搭——不是主花，但能让整束「会呼吸」。',
      '与尤加利、小雏菊同插；也可倒挂制干花。',
    ],
    occasions: ['森系', '配花', '干花'],
    colorLabel: '白黄',
    colorMeaning: '治愈、轻',
    pairing: [{ style: '森系', flowers: ['尤加利叶', '小雏菊'], note: '迷你白' }],
    caution: '瓣细易损；勤换水。',
    careSummary: '洋甘菊迷你扁瓣；勤换水，轻拿轻放。',
    careTips: ['可倒挂制干花'],
    bloomNote: '迷你菊，配花常用',
  }),
  spec('纽扣菊', 'Button', {
    scientificName: "Chrysanthemum 'Button'",
    namingNote: '纽扣状小菊，色彩多，配花高频',
    color: '多色，花头小、圆，如纽扣',
    scent: '几乎无香',
    featureRefs: ['trait.multi_head'],
    meaning: '点缀、色彩与「把空隙填满」',
    paragraphs: [
      '纽扣菊的价值在「填色」——主花之间的空隙，用它填满立刻热闹。',
      '耐插；枯谢小头及时剪除。',
    ],
    occasions: ['配花', '家居', '开业填充'],
    colorLabel: '多色',
    colorMeaning: '点缀、热闹',
    pairing: [{ style: '配花', flowers: ['玫瑰', '康乃馨'], note: '填色' }],
    caution: '枯谢小头及时剪除。',
    careSummary: '纽扣菊多色小头；勤换水，枯头及时剪。',
    careTips: ['枯谢小头及时剪除'],
    bloomNote: '配花小菊',
  }),
  spec('烟花菊', 'Firework', {
    scientificName: "Chrysanthemum 'Firework'",
    namingNote: '放射状瓣形，如烟花，秋日应季',
    color: '多色，瓣向外放射，线条感强',
    scent: '几乎无香',
    featureRefs: ['trait.spray_huge'],
    meaning: '绽放、秋日与「线条感很强的一束」',
    paragraphs: [
      '烟花菊的瓣形像定格的烟花——适合秋日、家居、以及想要「菊但不沉闷」的场景。',
      '耐插；与乒乓菊、尤加利对比，形态层次丰富。',
    ],
    occasions: ['秋日', '家居', '探望'],
    colorLabel: '多色',
    colorMeaning: '绽放、秋日',
    pairing: [{ style: '秋日', flowers: ['尤加利叶', '乒乓菊'], note: '形态对比' }],
    caution: '勤换水；放射瓣易折，轻拿轻放。',
    careSummary: '烟花菊放射瓣形；勤换水，轻拿轻放。',
    careTips: ['轻拿轻放'],
    bloomNote: '放射状菊，耐插',
  }),
  spec('非洲菊', 'Gerbera', {
    scientificName: 'Gerbera jamesonii',
    namingNote: '扁盘花型，色彩饱和，主花与配花皆宜',
    color: '多色，大圆盘，色调饱和明亮',
    scent: '几乎无香',
    featureRefs: ['trait.huge_flower', 'trait.classic_red'],
    meaning: '阳光、直接与「很亮的一朵」',
    paragraphs: [
      '非洲菊像「缩小版的向日葵盘」——适合生日、探望、开业，表达「开心、阳光」。',
      '花茎中空，宜高瓶支撑；勤换水，避免折茎。',
    ],
    occasions: ['生日', '探望', '开业', '家居'],
    colorLabel: '多色',
    colorMeaning: '阳光、快乐',
    pairing: [{ style: '阳光', flowers: ['向日葵', '绿康'], note: '明亮' }],
    caution: '茎中空易折；高瓶支撑。勤换水。',
    careSummary: '非洲菊扁盘花型；高瓶支撑，勤换水，避免折茎。',
    careTips: ['花茎中空，宜高瓶支撑'],
    bloomNote: '扁盘菊，色彩饱和',
  }),
]

const HYACINTH = [
  spec('蓝星', 'Blue Star', {
    scientificName: "Hyacinthus 'Blue Star'",
    namingNote: '蓝色风信子，穗形紧凑，春日浓香',
    color: '蓝色，穗形花序，花朵密集',
    scent: '浓香，室内明显',
    featureRefs: ['trait.strong_scent', 'trait.cool_season'],
    meaning: '春日、持久与「一进屋就闻到」',
    paragraphs: [
      '蓝星的风信子适合春日、家居——浓香是小空间里的「存在感」，过敏者慎选。',
      '浅水、冷凉；与粉、白风信子同插，色盘完整。',
    ],
    occasions: ['春日', '家居', '赠礼'],
    colorLabel: '蓝',
    colorMeaning: '宁静、春日',
    pairing: [{ style: '春日', flowers: ['粉珍珠', '白珍珠'], note: '蓝粉白' }],
    caution: '浓香；过敏者、密闭卧室慎选。',
    careSummary: '蓝星蓝色风信子；浅水、冷凉，浓香注意通风。',
    careTips: ['浓香，注意通风'],
    bloomNote: '蓝色风信子，约 7—10 天',
  }),
  spec('粉珍珠', 'Pink Pearl', {
    scientificName: "Hyacinthus 'Pink Pearl'",
    namingNote: '粉色风信子，温柔穗形',
    color: '柔粉，穗形，密集小朵',
    scent: '浓香',
    featureRefs: ['trait.strong_scent', 'trait.soft_pink'],
    meaning: '温柔、春日与「很甜的香气」',
    paragraphs: [
      '粉珍珠适合送女性、家居春日点缀——颜色比蓝星更软，但香气同样明显。',
      '与蓝星、白珍珠混搭，是经典风信子组合。',
    ],
    occasions: ['春日', '家居', '赠礼'],
    colorLabel: '柔粉',
    colorMeaning: '温柔、春日',
    pairing: [{ style: '组合', flowers: ['蓝星', '白珍珠'], note: '蓝粉白' }],
    caution: '浓香；过敏者慎选。',
    careSummary: '粉珍珠柔粉色风信子；浅水冷凉，保持通风。',
    careTips: ['保持通风'],
    bloomNote: '粉色风信子',
  }),
  spec('白珍珠', 'White Pearl', {
    scientificName: "Hyacinthus 'White Pearl'",
    namingNote: '白色风信子，洁净穗形',
    color: '纯白，穗形，密集',
    scent: '浓香',
    featureRefs: ['trait.strong_scent', 'trait.pure_white'],
    meaning: '纯洁、春日与「很干净的香」',
    paragraphs: [
      '白珍珠适合婚礼配花、家居——白穗形比百合更「春」，比玫瑰更「甜香」。',
      '浅水、冷凉；单品种插瓶也足够。',
    ],
    occasions: ['婚礼', '春日', '家居'],
    colorLabel: '纯白',
    colorMeaning: '纯洁、春日',
    pairing: [{ style: '婚礼', flowers: ['蓝星', '粉珍珠'], note: '白蓝粉' }],
    caution: '浓香；花粉敏感者慎选。',
    careSummary: '白珍珠白色风信子；浅水冷凉，勤换水。',
    careTips: ['勤换水'],
    bloomNote: '白色风信子',
  }),
  spec('吉普赛女王', 'Gypsy Queen', {
    scientificName: "Hyacinthus 'Gypsy Queen'",
    namingNote: '深粉紫风信子，个性色调',
    color: '深粉紫，穗形，色调偏个性',
    scent: '浓香',
    featureRefs: ['trait.strong_scent', 'trait.muted_retro'],
    meaning: '个性、春日与「不那么「标准」的风信子」',
    paragraphs: [
      '吉普赛女王色调更深——适合审美偏成熟、喜欢深色花材的人，与银叶、尤加利很搭。',
      '养护同风信子共通：浅水、冷凉、注意浓香。',
    ],
    occasions: ['纪念日', '家居', '个性赠礼'],
    colorLabel: '深粉紫',
    colorMeaning: '个性、成熟',
    pairing: [{ style: '个性', flowers: ['银芽柳', '尤加利叶'], note: '深色系' }],
    caution: '浓香；避暖气。',
    careSummary: '吉普赛女王深粉紫风信子；浅水冷凉，通风。',
    careTips: ['远离暖气'],
    bloomNote: '深粉紫风信子',
  }),
]

const CALLA = [
  spec('白马', 'White', {
    scientificName: "Zantedeschia 'White'",
    namingNote: '白色马蹄莲，线条干净，婚礼高频',
    color: '纯白佛焰苞，线条修长',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white', 'trait.cup_trumpet'],
    meaning: '纯洁、线条与「很现代的白」',
    paragraphs: [
      '白马马蹄莲的线条适合现代婚礼、极简家居——不是繁复的白，而是「一条干净的线」。',
      '佛焰苞易损，浅水、避免挤压；与绿康、尤加利极搭。',
    ],
    occasions: ['婚礼', '家居', '开业'],
    colorLabel: '纯白',
    colorMeaning: '纯洁、现代',
    pairing: [{ style: '极简', flowers: ['尤加利叶', '绿康'], note: '白绿' }],
    caution: '佛焰苞易损；浅水，勿挤压。',
    careSummary: '白马白色马蹄莲；浅水养护，轻拿轻放。',
    careTips: ['避免触碰挤压佛焰苞'],
    bloomNote: '白色马蹄莲',
  }),
  spec('黑魔法', 'Black Magic', {
    scientificName: "Zantedeschia 'Black Magic'",
    namingNote: '深紫近黑马蹄莲，个性高级',
    color: '深紫近黑佛焰苞，线条挺括',
    scent: '几乎无香',
    featureRefs: ['trait.muted_retro'],
    meaning: '神秘、个性与「马蹄莲里的暗夜」',
    paragraphs: [
      '黑魔法适合酷感花束、纪念日——与白色马蹄莲对比，同一束里极有张力。',
      '养护同马蹄莲：浅水、轻拿轻放。',
    ],
    occasions: ['纪念日', '个性赠礼', '拍照'],
    colorLabel: '深紫近黑',
    colorMeaning: '神秘、高级',
    pairing: [{ style: '对比', flowers: ['白马', '银芽柳'], note: '黑白' }],
    caution: '佛焰苞易损；浅水。',
    careSummary: '黑魔法深紫马蹄莲；浅水，轻拿轻放。',
    careTips: ['轻拿轻放'],
    bloomNote: '深紫马蹄莲',
  }),
  spec('粉钻', 'Pink Diamond', {
    scientificName: "Zantedeschia 'Pink Diamond'",
    namingNote: '粉色马蹄莲，温柔线条',
    color: '柔粉佛焰苞，线条优雅',
    scent: '几乎无香',
    featureRefs: ['trait.soft_pink'],
    meaning: '温柔、现代与「很柔的一条线」',
    paragraphs: [
      '粉钻马蹄莲适合婚礼、家居——比玫瑰更「线」，比百合更「简」。',
      '与白色、绿色配花同插，色调干净。',
    ],
    occasions: ['婚礼', '家居', '赠礼'],
    colorLabel: '柔粉',
    colorMeaning: '温柔、优雅',
    pairing: [{ style: '婚礼', flowers: ['白马', '尤加利叶'], note: '粉白绿' }],
    caution: '勿挤压佛焰苞；浅水。',
    careSummary: '粉钻粉色马蹄莲；浅水，轻拿轻放。',
    careTips: ['浅水养护'],
    bloomNote: '粉色马蹄莲',
  }),
  spec('黄金', 'Golden', {
    scientificName: "Zantedeschia 'Golden'",
    namingNote: '黄色马蹄莲，明亮少见',
    color: '明亮黄色佛焰苞，线条挺括',
    scent: '几乎无香',
    featureRefs: ['trait.yellow_gold'],
    meaning: '明亮、现代与「马蹄莲里的阳光」',
    paragraphs: [
      '黄色马蹄莲相对少见——适合开业、生日，以及想要「线条感 + 明亮色」。',
      '与白色、绿色同插，视觉干净。',
    ],
    occasions: ['开业', '生日', '家居'],
    colorLabel: '黄',
    colorMeaning: '明亮、祝福',
    pairing: [{ style: '明亮', flowers: ['绿康', '白马'], note: '黄白绿' }],
    caution: '佛焰苞易损；浅水。',
    careSummary: '黄金黄色马蹄莲；浅水，轻拿轻放。',
    careTips: ['避免挤压'],
    bloomNote: '黄色马蹄莲',
  }),
]

const SUNFLOWER = [
  spec('泰迪熊', 'Teddy Bear', {
    scientificName: "Helianthus 'Teddy Bear'",
    alias: 'Teddy Bear',
    namingNote: '重瓣矮生向日葵，花市常称「迷你向日葵」；花瓣层叠蓬松，整体如毛绒小圆盘',
    color: '正黄至金黄，重瓣堆叠如毛绒小球，几乎不见典型大深色花盘',
    scent: '几乎无香',
    flowerForm: ['trait.spray_ball'],
    bloomDiameterCm: '6 至 10',
    stem: '茎相对矮壮，节间较短，花头仍偏重，建议中高瓶支撑',
    featureRefs: ['trait.yellow_gold', 'trait.spray_ball'],
    meaning: '可爱、阳光与「毛绒绒的小太阳」',
    paragraphs: [
      '它的金黄色调不像标准向日葵那样铺张外放，而是堆叠在小小的重瓣花盘里，像一颗可以捧在手心的「小太阳」。花市里常说的迷你向日葵，多半指的就是这类泰迪熊型重瓣矮生切花——比文森特更小、更圆、更蓬松，少了大花盘的压迫感，却保留了向日葵标志性的明亮与积极。',
      '它很适合送给朋友、同学或小朋友，毕业季、生日、乔迁或只是想给桌面添一点阳光时都很得体。与尤加利、小雏菊或绿康同插，黄白绿层次清爽；单独几支放进中小号花瓶，也能做出可爱而不幼稚的家居点缀。花头虽不大，仍建议中高瓶支撑并勤换水，才能让这层叠的重瓣尽量保持蓬松开放。',
    ],
    occasions: ['送朋友', '毕业', '生日', '家居', '探望', '儿童节'],
    colorLabel: '金黄',
    colorMeaning: '可爱、阳光；比标准向日葵更柔和亲近',
    pairing: [
      { style: '可爱森系', flowers: ['小雏菊', '尤加利叶'], note: '黄白绿，适合生日或日常桌面' },
      { style: '毕业庆祝', flowers: ['绿康', '满天星'], note: '明亮而不喧闹，迷你花盘更适合手持或中小花束' },
    ],
    caution: '花头仍偏重，勿用过低花瓶；重瓣结构怕挤压，运输与插瓶时轻拿轻放。',
    careSummary: '迷你向日葵（泰迪熊）重瓣团状，花头仍偏重；中高瓶支撑，勤换水。',
    careTips: ['花盘虽小仍偏重，建议中高瓶支撑', '重瓣结构易藏水，换水时轻晃花头帮助排水'],
    bloomNote: '重瓣矮生迷你向日葵，花盘小但吸水需求不低',
    diffPeers: {
      文森特: '标准切花向日葵，单瓣感强、花盘大，花径明显大于迷你款',
      黑芯向日葵: '典型大花盘配深色花心，轮廓扁平开阔，非重瓣毛绒团状',
    },
    selfDiff: '重瓣矮生、花盘小、轮廓毛绒，迷你向日葵辨识度最高',
  }),
  spec('文森特', 'Vincent', {
    scientificName: "Helianthus 'Vincent'",
    namingNote: '标准切花向日葵，花盘大、经典',
    color: '金黄花盘，深色花心，茎干粗壮',
    scent: '几乎无香',
    featureRefs: ['trait.yellow_gold', 'trait.huge_flower'],
    meaning: '阳光、经典与「最像向日葵的一朵」',
    paragraphs: [
      '文森特是花店「标准向日葵」——适合开业、生日、探望，表达「阳光、积极」。',
      '花盘重，必须高瓶；勤换水保证吸水。',
    ],
    occasions: ['开业', '生日', '探望', '庆典'],
    colorLabel: '金黄',
    colorMeaning: '阳光、积极',
    pairing: [{ style: '开业', flowers: ['绿康', '百合'], note: '明亮' }],
    caution: '花盘重；高瓶支撑。',
    careSummary: '文森特标准向日葵；高瓶支撑，勤换水。',
    careTips: ['高瓶支撑', '勤换水'],
    bloomNote: '标准向日葵',
  }),
  spec('黑芯向日葵', 'Black Core', {
    scientificName: "Helianthus 'Black Core'",
    namingNote: '深色花心向日葵，对比更强',
    color: '金黄瓣，花心深近黑，对比强',
    scent: '几乎无香',
    featureRefs: ['trait.yellow_gold'],
    meaning: '阳光、个性与「更有态度的太阳」',
    paragraphs: [
      '黑芯向日葵比标准款更「酷」一点——适合年轻人、拍照、以及想要向日葵但不想太「村」。',
      '养护同向日葵：高瓶、勤换水。',
    ],
    occasions: ['生日', '拍照', '开业', '家居'],
    colorLabel: '金黄+深芯',
    colorMeaning: '阳光、个性',
    pairing: [{ style: '酷感', flowers: ['尤加利叶', '银芽柳'], note: '黄绿灰' }],
    caution: '高瓶支撑；勤换水。',
    careSummary: '黑芯向日葵；高瓶支撑，勤换水。',
    careTips: ['高瓶支撑'],
    bloomNote: '深芯向日葵',
  }),
  spec('奶油向日葵', 'Cream', {
    scientificName: "Helianthus 'Cream'",
    namingNote: '奶油色瓣向日葵，低饱和温柔',
    color: '奶油黄瓣，色调低饱和，更温柔',
    scent: '几乎无香',
    featureRefs: ['trait.champagne_tone', 'trait.yellow_gold'],
    meaning: '温柔、阳光与「不刺眼的亮」',
    paragraphs: [
      '奶油向日葵适合婚礼、家居——有向日葵的形，但没有那么「黄」，更莫兰迪、更温柔。',
      '与白色、绿色花材同插，色调高级。',
    ],
    occasions: ['婚礼', '家居', '纪念日'],
    colorLabel: '奶油黄',
    colorMeaning: '温柔、阳光',
    pairing: [{ style: '婚礼', flowers: ['白玫瑰', '尤加利叶'], note: '奶油白绿' }],
    caution: '高瓶支撑；勤换水。',
    careSummary: '奶油色向日葵；高瓶支撑，勤换水。',
    careTips: ['高瓶支撑'],
    bloomNote: '奶油色向日葵',
  }),
]

module.exports = {
  ...exportKind('菊花', CHRYS),
  ...exportKind('风信子', HYACINTH),
  ...exportKind('马蹄莲', CALLA),
  ...exportKind('向日葵', SUNFLOWER),
}
