const { exportKind } = require('./shared')

function spec(variety, alias, extra) {
  return { variety, alias, ...extra }
}

const EUSTOMA = [
  spec('露西塔系列', 'Rosita', {
    scientificName: "Eustoma 'Rosita'",
    namingNote: '洋桔梗露西塔系列，瓣形规整，婚礼与日常高频',
    color: '多色，喇叭杯形，瓣缘柔和',
    scent: '几乎无香',
    featureRefs: ['trait.cup_trumpet', 'trait.soft_pink'],
    meaning: '温柔、优雅与「很轻的主花」',
    paragraphs: [
      '露西塔系列瓣形规整——适合婚礼、日常家居，单品种插瓶也足够优雅。',
      '花瓣娇嫩，轻拿轻放；清洁水质，避免挤压折瓣。',
    ],
    occasions: ['婚礼', '日常家居', '赠礼'],
    colorLabel: '多色',
    colorMeaning: '优雅、温柔',
    pairing: [{ style: '婚礼', flowers: ['玫瑰', '翠珠'], note: '轻粉白' }],
    caution: '花瓣娇嫩；避免挤压与花瓣沾水。',
    careSummary: '露西塔洋桔梗瓣形规整；轻拿轻放，清洁水质。',
    careTips: ['轻拿轻放', '避免挤压折瓣'],
    bloomNote: '洋桔梗系列，约 7—12 天',
  }),
  spec('波浪系列', 'Wave', {
    scientificName: "Eustoma 'Wave'",
    namingNote: '瓣缘波浪状洋桔梗，形态更柔',
    color: '多色，瓣缘呈波浪，整体轻盈',
    scent: '几乎无香',
    featureRefs: ['trait.soft_pink', 'trait.cup_trumpet'],
    meaning: '轻盈、浪漫与「瓣缘会动的美」',
    paragraphs: [
      '波浪系列的辨识度在瓣缘——适合法式、浪漫系花束，与蕾丝花、小菊极搭。',
      '养护同洋桔梗：轻拿、清洁水、避挤压。',
    ],
    occasions: ['婚礼', '法式', '家居'],
    colorLabel: '多色',
    colorMeaning: '浪漫、轻盈',
    pairing: [{ style: '法式', flowers: ['蕾丝花', '小雏菊'], note: '轻' }],
    caution: '瓣缘易损；轻拿轻放。',
    careSummary: '波浪系列洋桔梗；轻拿轻放，清洁水质。',
    careTips: ['避免挤压瓣缘'],
    bloomNote: '波浪洋桔梗',
  }),
  spec('花束系列', 'Bouquet', {
    scientificName: "Eustoma 'Bouquet'",
    namingNote: '多朵同枝洋桔梗，花量大',
    color: '多色，同一枝多朵，花量感强',
    scent: '几乎无香',
    featureRefs: ['trait.multi_head', 'trait.spray_huge'],
    meaning: '花量、实惠与「一束很多朵」',
    paragraphs: [
      '花束系列适合预算有限但想要「看起来很多」——同一枝多朵开放，家居与配花都常用。',
      '预留瓶口空间；枯谢小头及时剪除。',
    ],
    occasions: ['家居', '配花', '预算友好'],
    colorLabel: '多色',
    colorMeaning: '花量、实惠',
    pairing: [{ style: '满瓶', flowers: ['尤加利叶'], note: '单品种' }],
    caution: '预留瓶口；轻拿轻放。',
    careSummary: '花束系列洋桔梗多朵同枝；预留瓶口，轻拿轻放。',
    careTips: ['枯谢小头及时剪除'],
    bloomNote: '多头洋桔梗',
  }),
]

const GYP = [
  spec('仙女', 'Gypsophila', {
    scientificName: 'Gypsophila paniculata',
    namingNote: '标准白色满天星，配花之王',
    color: '纯白细碎小花，整体雾状',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white', 'trait.spray_huge'],
    meaning: '陪伴、纯净与「把主花托起来」',
    paragraphs: [
      '仙女满天星是配花之王——几乎任何主花加它，层次立刻完整；也可单品种做干花。',
      '耐插；保持通风，可倒挂制干花。',
    ],
    occasions: ['配花', '婚礼', '干花'],
    colorLabel: '纯白',
    colorMeaning: '纯净、陪伴',
    pairing: [{ style: '配花', flowers: ['玫瑰', '康乃馨'], note: '万能' }],
    caution: '易闷湿；通风。可制干花。',
    careSummary: '仙女白色满天星；清洁水质，通风，可制干花。',
    careTips: ['可倒挂制干花'],
    bloomNote: '白色满天星，耐插',
  }),
  spec('百万星', 'Million Star', {
    scientificName: "Gypsophila 'Million Star'",
    namingNote: '密集小星点满天星，花量更大',
    color: '白色，花点更密更细',
    scent: '几乎无香',
    featureRefs: ['trait.spray_huge'],
    meaning: '密集、雾感与「更满的星空」',
    paragraphs: [
      '百万星比标准仙女更密——适合想要「雾更大」的婚礼与包装；同样适合干花。',
      '通风、清洁水；避免挤压。',
    ],
    occasions: ['婚礼', '配花', '干花'],
    colorLabel: '白',
    colorMeaning: '密集、梦幻',
    pairing: [{ style: '婚礼', flowers: ['玫瑰', '尤加利叶'], note: '雾感' }],
    caution: '通风；可制干花。',
    careSummary: '百万星密集满天星；通风，清洁水质。',
    careTips: ['可制干花'],
    bloomNote: '密集满天星',
  }),
  spec('粉满天星', 'Pink', {
    scientificName: "Gypsophila 'Pink'",
    namingNote: '染色调粉色满天星，少女系配花',
    color: '粉色雾状，整体轻盈',
    scent: '几乎无香',
    featureRefs: ['trait.soft_pink'],
    meaning: '少女、梦幻与「粉色的雾」',
    paragraphs: [
      '粉满天星适合生日、送女生、少女系花束——比白满天星更「甜」。',
      '多为染色处理，勤换水；可制干花保留颜色。',
    ],
    occasions: ['生日', '送女生', '配花'],
    colorLabel: '粉',
    colorMeaning: '少女、梦幻',
    pairing: [{ style: '少女', flowers: ['粉钻', '玫瑰'], note: '粉系' }],
    caution: '染色品种勤换水；避阳光直射褪色。',
    careSummary: '粉满天星；勤换水，通风，可制干花。',
    careTips: ['避直射防褪色'],
    bloomNote: '粉色满天星',
  }),
  spec('蓝满天星', 'Blue', {
    scientificName: "Gypsophila 'Blue'",
    namingNote: '染色调蓝色满天星，个性配花',
    color: '蓝色雾状，视觉清凉',
    scent: '几乎无香',
    featureRefs: ['trait.muted_retro'],
    meaning: '清凉、个性与「蓝色的雾」',
    paragraphs: [
      '蓝满天星适合酷感、现代风花束——与白色、银色花材极搭。',
      '染色品种，勤换水；可制干花。',
    ],
    occasions: ['个性花束', '配花', '干花'],
    colorLabel: '蓝',
    colorMeaning: '清凉、个性',
    pairing: [{ style: '酷感', flowers: ['白玫瑰', '银芽柳'], note: '蓝白' }],
    caution: '染色品种勤换水。',
    careSummary: '蓝满天星；勤换水，通风。',
    careTips: ['可制干花'],
    bloomNote: '蓝色满天星',
  }),
]

module.exports = {
  ...exportKind('洋桔梗', EUSTOMA),
  ...exportKind('满天星', GYP),
}
