const { exportKind } = require('./shared')

function spec(variety, alias, extra) {
  return { variety, alias, ...extra }
}

const FOLIAGE = [
  spec('尤加利', 'Eucalyptus', {
    scientificName: 'Eucalyptus spp.',
    namingNote: '最常用配叶，森系/北欧/开业花束几乎必备',
    color: '灰绿叶片，线条修长，整体清凉',
    scent: '几乎无花香气，叶片有清凉叶香',
    featureRefs: ['trait.cut_foliage', 'trait.muted_retro'],
    meaning: '层次、森系与「把主花托起来」',
    paragraphs: [
      '尤加利是花店万能配叶——几乎任何主花加它，立刻有层次和风格；部分品种可倒挂制干花。',
      '保持清洁水质与通风；叶材收到后斜剪根部即可。',
    ],
    occasions: ['配花', '森系', '干花', '开业'],
    colorLabel: '灰绿',
    colorMeaning: '清凉、层次',
    pairing: [{ style: '森系', flowers: ['玫瑰', '洋桔梗'], note: '万能配叶' }],
    caution: '部分品种可制干花；勤换水，通风。',
    careSummary: '尤加利为常用配叶，保持清洁水质与通风，部分品种可倒挂制干花。',
    careTips: ['可倒挂风干制干花'],
    bloomNote: '叶材保持清洁水质与通风',
  }),
  spec('龟背竹', 'Monstera', {
    scientificName: 'Monstera deliciosa',
    namingNote: '大叶配材，热带风、开业与家居常见',
    color: '深绿大叶，裂刻明显，热带感强',
    scent: '几乎无香',
    featureRefs: ['trait.tropical_leaf'],
    meaning: '热带、线条与「很大气的叶」',
    paragraphs: [
      '龟背竹叶适合热带风、现代开业花束——一片叶就能定调，与白色、绿色花材极搭。',
      '叶缘易损，轻拿；清洁水质，避免叶浸水过久。',
    ],
    occasions: ['开业', '热带风', '家居'],
    colorLabel: '深绿',
    colorMeaning: '热带、大气',
    pairing: [{ style: '热带', flowers: ['白玫瑰', '绿康'], note: '绿白' }],
    caution: '叶大易损；轻拿轻放。',
    careSummary: '龟背竹叶材；清洁水质，轻拿轻放，避免浸水过久。',
    careTips: ['避免叶片长期浸水'],
    bloomNote: '叶材，清洁水质',
  }),
  spec('雪柳', 'Spiraea', {
    scientificName: 'Spiraea thunbergii',
    namingNote: '春季线性花材，白色细枝，野趣高级',
    color: '白色细花沿枝开放，线条线性',
    scent: '淡香',
    featureRefs: ['trait.pure_white'],
    meaning: '春日、线性美与「很轻的满枝白」',
    paragraphs: [
      '雪柳是春日限定的高级线条——适合自然风、日式、开业，与郁金香、小菊同插极美。',
      '勤换水；线性枝条注意瓶口空间。',
    ],
    occasions: ['春日', '自然风', '开业', '婚礼'],
    colorLabel: '白',
    colorMeaning: '春日、线性',
    pairing: [{ style: '春日', flowers: ['郁金香', '小雏菊'], note: '线性' }],
    caution: '春季应季；勤换水。',
    careSummary: '雪柳线性花材；勤换水，保持通风。',
    careTips: ['预留瓶口空间'],
    bloomNote: '春季线性花材',
  }),
  spec('银芽柳', 'Silver Willow', {
    scientificName: 'Salix caprea',
    namingNote: '银灰色绒芽，现代与酷感花束常用',
    color: '银灰绒芽，线条挺括',
    scent: '几乎无香',
    featureRefs: ['trait.muted_retro'],
    meaning: '现代、酷感与「银灰的线条」',
    paragraphs: [
      '银芽柳适合现代、酷感花束——与深色系花材、尤加利同插，整束立刻「高级灰」。',
      '也可干插；勤换水。',
    ],
    occasions: ['现代风', '酷感', '干花', '开业'],
    colorLabel: '银灰',
    colorMeaning: '现代、高级',
    pairing: [{ style: '酷感', flowers: ['夜皇后', '野马'], note: '银灰+深' }],
    caution: '可干插；勤换水。',
    careSummary: '银芽柳；清洁水质，可干插观赏。',
    careTips: ['可干插'],
    bloomNote: '银灰线性花材',
  }),
  spec('散尾葵', 'Areca Palm', {
    scientificName: 'Dypsis lutescens',
    namingNote: '羽状叶配材，热带开业常见',
    color: '羽状深绿叶，热带感',
    scent: '几乎无香',
    featureRefs: ['trait.tropical_leaf'],
    meaning: '热带、开业与「很大气的羽叶」',
    paragraphs: [
      '散尾葵叶适合开业、热带风——与白色百合、绿康同插，气场足。',
      '叶材清洁水质；避免叶浸水腐烂。',
    ],
    occasions: ['开业', '热带风'],
    colorLabel: '深绿',
    colorMeaning: '热带、气场',
    pairing: [{ style: '开业', flowers: ['百合', '绿康'], note: '热带' }],
    caution: '避免叶长期浸水。',
    careSummary: '散尾葵配叶；清洁水质，避免浸水腐烂。',
    careTips: ['去除浸水叶片'],
    bloomNote: '羽状配叶',
  }),
  spec('米兰叶', 'Aglaia', {
    scientificName: 'Aglaia odorata',
    namingNote: '深绿小圆叶，中式与开业常用配叶',
    color: '深绿小圆叶，整体紧凑',
    scent: '叶有淡香',
    featureRefs: ['trait.cut_foliage'],
    meaning: '中式、喜庆与「很传统的配叶」',
    paragraphs: [
      '米兰叶常见于中式开业、贺礼花束——与红色主花、百合极搭，表达「喜庆、圆满」。',
      '清洁水质；勤换水。',
    ],
    occasions: ['开业', '贺寿', '中式'],
    colorLabel: '深绿',
    colorMeaning: '喜庆、传统',
    pairing: [{ style: '中式', flowers: ['红富士', '百合'], note: '红绿' }],
    caution: '勤换水；通风。',
    careSummary: '米兰叶配叶；清洁水质，勤换水。',
    careTips: ['勤换水'],
    bloomNote: '中式配叶',
  }),
  spec('栀子叶', 'Gardenia Leaf', {
    scientificName: 'Gardenia jasminoides',
    namingNote: '深绿厚叶，与白色花材绝配',
    color: '深绿厚叶，革质有光泽',
    scent: '几乎无香',
    featureRefs: ['trait.cut_foliage'],
    meaning: '衬托、洁净与「让白更白」',
    paragraphs: [
      '栀子叶常用来衬托白色花材——与白玫瑰、白百合、马蹄莲同插，白色更干净。',
      '厚叶耐插；清洁水质即可。',
    ],
    occasions: ['配花', '婚礼', '家居'],
    colorLabel: '深绿',
    colorMeaning: '衬托、洁净',
    pairing: [{ style: '白绿', flowers: ['白梦', '白马'], note: '白绿' }],
    caution: '清洁水质；避免叶浸水。',
    careSummary: '栀子叶厚叶配材；清洁水质，去除浸水叶。',
    careTips: ['去除浸水叶片'],
    bloomNote: '厚叶配材',
  }),
]

const POTTED = [
  spec('蝴蝶兰', 'Phalaenopsis', {
    scientificName: 'Phalaenopsis spp.',
    namingNote: '高端盆栽礼品，花期长，办公室与家居常见',
    color: '多色，蝴蝶形花朵，序列开放',
    scent: '淡香或几乎无香',
    featureRefs: ['trait.huge_flower', 'trait.potted_gift'],
    meaning: '高雅、长久与「可养可赏的礼品」',
    paragraphs: [
      '蝴蝶兰是盆栽礼品代表——适合开业、贺寿、商务赠礼，强调「可以养很久」。',
      '见干见湿，明亮散射光，忌叶心长期积水；礼品包装注意底部通风。',
    ],
    occasions: ['开业', '贺寿', '商务礼品', '家居'],
    colorLabel: '多色',
    colorMeaning: '高雅、长久',
    pairing: [{ style: '礼品', flowers: [], note: '单盆即可' }],
    caution: '忌叶心积水；忌暴晒与闷根。',
    careSummary: '蝴蝶兰以盆栽观赏为主，见干见湿、明亮散射光、忌积水。',
    careTips: ['忌叶心长期积水', '礼品包装注意底部通风'],
    bloomNote: '盆栽观赏因品种而异',
  }),
  spec('富贵竹', 'Lucky Bamboo', {
    scientificName: 'Dracaena sanderiana',
    namingNote: '水培/土培皆可，开业与家居极常见',
    color: '绿色茎叶，常水培',
    scent: '几乎无香',
    featureRefs: ['trait.potted_gift'],
    meaning: '吉祥、节节高与「很好养的绿」',
    paragraphs: [
      '富贵竹是开业、乔迁、办公桌经典——寓意好、养护简单，水培或土培皆可。',
      '水培须定期换水；土培见干见湿。',
    ],
    occasions: ['开业', '乔迁', '办公', '家居'],
    colorLabel: '绿',
    colorMeaning: '吉祥、节节高',
    pairing: [{ style: '开业', flowers: [], note: '单盆即可' }],
    caution: '水培定期换水；避免暴晒。',
    careSummary: '富贵竹见干见湿或清洁水培，明亮散射光，忌积水。',
    careTips: ['水培定期换水'],
    bloomNote: '盆栽观赏',
  }),
  spec('发财树', 'Pachira', {
    scientificName: 'Pachira aquatica',
    namingNote: '大型盆栽，开业礼品常见',
    color: '掌状绿叶，株形大气',
    scent: '几乎无香',
    featureRefs: ['trait.tropical_leaf', 'trait.potted_gift'],
    meaning: '招财、气场与「很大的一盆绿」',
    paragraphs: [
      '发财树适合开业、乔迁——株形大气，寓意明确；适合前台、客厅。',
      '见干见湿，忌积水；明亮散射光。',
    ],
    occasions: ['开业', '乔迁', '办公'],
    colorLabel: '绿',
    colorMeaning: '招财、气场',
    pairing: [{ style: '开业', flowers: [], note: '单盆即可' }],
    caution: '忌积水；冬季减少浇水。',
    careSummary: '发财树见干见湿，明亮散射光，忌积水。',
    careTips: ['忌积水闷根'],
    bloomNote: '盆栽观赏',
  }),
  spec('龟背竹盆栽', 'Monstera Potted', {
    scientificName: 'Monstera deliciosa',
    namingNote: '观叶盆栽，北欧家居热门',
    color: '深绿裂刻叶，热带北欧风',
    scent: '几乎无香',
    featureRefs: ['trait.tropical_leaf', 'trait.potted_gift'],
    meaning: '家居、格调与「很好看的叶」',
    paragraphs: [
      '龟背竹盆栽是家居网红——适合喜欢绿植但不想太「传统」的人，与北欧、现代风空间极搭。',
      '见干见湿，散射光，忌积水。',
    ],
    occasions: ['家居', '乔迁', '赠礼'],
    colorLabel: '深绿',
    colorMeaning: '格调、家居',
    pairing: [{ style: '家居', flowers: [], note: '单盆即可' }],
    caution: '忌积水与暴晒。',
    careSummary: '龟背竹盆栽见干见湿，明亮散射光，忌积水。',
    careTips: ['忌积水'],
    bloomNote: '盆栽观赏',
  }),
  spec('多肉', 'Succulent', {
    scientificName: 'Succulent mix',
    namingNote: '组合多肉盆栽，低维护礼品',
    color: '多色肉质叶，组合盆栽',
    scent: '几乎无香',
    featureRefs: ['trait.potted_gift'],
    meaning: '治愈、低维护与「桌面小生态」',
    paragraphs: [
      '多肉组合适合送同事、学生、桌面——养护简单，「少浇水」反而是优点。',
      '见干见湿，通风，忌积水；夏季避暴晒。',
    ],
    occasions: ['送同事', '桌面', '家居', '赠礼'],
    colorLabel: '多色',
    colorMeaning: '治愈、低维护',
    pairing: [{ style: '桌面', flowers: [], note: '单盆即可' }],
    caution: '忌积水；夏季通风避暴晒。',
    careSummary: '多肉见干见湿，通风，忌积水。',
    careTips: ['少浇水', '夏季避暴晒'],
    bloomNote: '盆栽观赏',
  }),
  spec('茉莉花', 'Jasmine', {
    scientificName: 'Jasminum sambac',
    namingNote: '观花闻香盆栽，夏季常见',
    color: '白色小花，叶片深绿',
    scent: '浓香，夏季明显',
    featureRefs: ['trait.strong_scent', 'trait.pure_white'],
    meaning: '清香、日常与「可闻可看的盆栽」',
    paragraphs: [
      '茉莉花盆栽适合喜欢花香的人——夏季开放，阳台、窗台都很合适；与纯切花不同，是「可以养很久的香」。',
      '见干见湿，充足光照；开花期可施薄肥。',
    ],
    occasions: ['家居', '阳台', '赠礼'],
    colorLabel: '白',
    colorMeaning: '清香、日常',
    pairing: [{ style: '阳台', flowers: [], note: '单盆即可' }],
    caution: '浓香；需要充足光照才易开花。',
    careSummary: '茉莉花盆栽见干见湿，充足光照，花期可施薄肥。',
    careTips: ['充足光照易开花'],
    bloomNote: '盆栽观赏',
  }),
]

const SMALL = [
  spec('花毛茛', 'Ranunculus', {
    scientificName: 'Ranunculus asiaticus',
    namingNote: '洋牡丹/花毛茛，层叠如纸，春日高端',
    color: '多色，重瓣层叠，开放后如纸花',
    scent: '淡香',
    featureRefs: ['trait.huge_flower', 'trait.soft_pink'],
    distinguishFrom: [
      { name: '牡丹', difference: '木本牡丹花更大、茎更粗，而非切花洋牡丹' },
      { name: '玫瑰', difference: '杯状月季，而非层叠纸感瓣形' },
      { name: '花毛茛', difference: '层叠如纸的瓣形，是春日高端切花代表' },
    ],
    meaning: '春日、精致与「层叠的纸感美」',
    paragraphs: [
      '花毛茛是春日高端切花——层叠瓣形像纸做的一般，适合婚礼、纪念日。',
      '茎纤细，轻拿；清洁水质，避挤压。',
    ],
    occasions: ['婚礼', '春日', '纪念日'],
    colorLabel: '多色',
    colorMeaning: '精致、春日',
    pairing: [{ style: '婚礼', flowers: ['郁金香', '翠珠'], note: '春日' }],
    caution: '瓣娇嫩；轻拿轻放。',
    careSummary: '花毛茛层叠瓣形；轻拿轻放，清洁水质。',
    careTips: ['避免挤压'],
    bloomNote: '约 5—7 天',
  }),
  spec('银莲花', 'Anemone', {
    scientificName: 'Anemone coronaria',
    namingNote: '单瓣/重瓣银莲花，春日线条美',
    color: '多色，黑芯或色芯，瓣形简洁',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white', 'trait.classic_red'],
    distinguishFrom: [
      { name: '郁金香', difference: '杯状线条，而非黑芯简洁瓣形' },
      { name: '洋桔梗', difference: '喇叭杯形，而非银莲花式黑芯' },
      { name: '银莲花', difference: '黑芯简洁瓣形，是法式春日花束高频' },
    ],
    meaning: '春日、简洁与「很干净的一朵」',
    paragraphs: [
      '银莲花线条简洁——适合法式、日式春日花束，与郁金香、小菊同插。',
      '轻拿；清洁水质，喜冷凉。',
    ],
    occasions: ['春日', '婚礼', '法式'],
    colorLabel: '多色',
    colorMeaning: '简洁、春日',
    pairing: [{ style: '法式', flowers: ['郁金香', '蕾丝花'], note: '春日' }],
    caution: '喜冷凉；瓣易损。',
    careSummary: '银莲花；轻拿轻放，清洁水质，冷凉环境。',
    careTips: ['喜冷凉'],
    bloomNote: '约 5—7 天',
  }),
  spec('翠珠', 'Green Bell', {
    scientificName: 'Greenbell',
    namingNote: '绿色小球配花，独特可爱',
    color: '绿色小球沿细枝，整体轻盈',
    scent: '几乎无香',
    featureRefs: ['trait.green_orb'],
    distinguishFrom: [
      { name: '满天星', difference: '白色雾状细花，而非绿色小球' },
      { name: '尤加利叶', difference: '叶材线条，而非小球花苞' },
      { name: '翠珠', difference: '绿色小球沿枝，是近年热门配花' },
    ],
    meaning: '独特、配花与「绿色的小星球」',
    paragraphs: [
      '翠珠是近年很红的配花——绿色小球独特，与粉、白主花同插，立刻有「会呼吸的绿」。',
      '清洁水质；通风。',
    ],
    occasions: ['配花', '婚礼', '家居'],
    colorLabel: '绿',
    colorMeaning: '独特、清新',
    pairing: [{ style: '配花', flowers: ['玫瑰', '洋桔梗'], note: '绿+粉白' }],
    caution: '勤换水；通风。',
    careSummary: '翠珠配花；清洁水质，通风。',
    careTips: ['勤换水'],
    bloomNote: '约 7—10 天',
  }),
  spec('蕾丝花', 'Orlaya', {
    scientificName: 'Orlaya grandiflora',
    namingNote: '白色伞形配花，法式野趣',
    color: '白色伞形小花，轻盈',
    scent: '淡香',
    featureRefs: ['trait.pure_white'],
    distinguishFrom: [
      { name: '小雏菊', difference: '扁瓣菊形，而非伞形细花' },
      { name: '满天星', difference: '雾状密点，而非伞形轮廓' },
      { name: '蕾丝花', difference: '白色伞形，是法式野趣标配' },
    ],
    meaning: '轻灵、法式与「雾状的白」',
    paragraphs: [
      '蕾丝花是法式野趣标配——与郁金香、小菊、尤加利同插，整束立刻「会呼吸」。',
      '清洁水质；也可制干花。',
    ],
    occasions: ['婚礼', '法式', '野趣'],
    colorLabel: '白',
    colorMeaning: '轻灵、纯洁',
    pairing: [{ style: '法式', flowers: ['小雏菊', '尤加利叶'], note: '白绿' }],
    caution: '轻盈易损；勤换水。',
    careSummary: '蕾丝花伞形配花；清洁水质，轻拿轻放。',
    careTips: ['可制干花'],
    bloomNote: '约 7—10 天',
  }),
  spec('紫罗兰', 'Matthiola', {
    scientificName: 'Matthiola incana',
    namingNote: '穗形紫罗兰，浓香，春日应季',
    color: '多色，穗形花序',
    scent: '浓香',
    featureRefs: ['trait.strong_scent'],
    distinguishFrom: [
      { name: '风信子', difference: '球状穗更粗，而非紫罗兰式长穗' },
      { name: '洋桔梗', difference: '单朵杯形，而非穗形花序' },
      { name: '紫罗兰', difference: '穗形浓香，有复古花店气质' },
    ],
    meaning: '春日、浓香与「很复古的一穗」',
    paragraphs: [
      '紫罗兰适合喜欢浓香、复古感的人——春日应季，与郁金香、小菊同插有老派花店气质。',
      '勤换水；通风；过敏者慎选。',
    ],
    occasions: ['春日', '家居', '复古'],
    colorLabel: '多色',
    colorMeaning: '复古、浓香',
    pairing: [{ style: '复古', flowers: ['郁金香', '康乃馨'], note: '春日' }],
    caution: '浓香；过敏者慎选。',
    careSummary: '紫罗兰穗形；勤换水，通风。',
    careTips: ['浓香，注意通风'],
    bloomNote: '约 5—7 天',
  }),
  spec('勿忘我', 'Myosotis', {
    scientificName: 'Myosotis sylvatica',
    namingNote: '蓝色细碎小花，干花与配花常用',
    color: '蓝色细碎，整体星点状',
    scent: '几乎无香',
    featureRefs: ['trait.tiny_cluster'],
    distinguishFrom: [
      { name: '满天星', difference: '白色雾状，而非蓝色星点' },
      { name: '翠珠', difference: '绿色小球，而非蓝色细花' },
      { name: '勿忘我', difference: '蓝色细碎，常作「记得你」配花或干花' },
    ],
    meaning: '记忆、陪伴与「很小的一束蓝」',
    paragraphs: [
      '勿忘我常作配花或干花——表达「记得你」；与玫瑰、满天星同插，或倒挂制干花保留。',
      '清洁水质；可制干花。',
    ],
    occasions: ['配花', '干花', '纪念'],
    colorLabel: '蓝',
    colorMeaning: '记忆、陪伴',
    pairing: [{ style: '配花', flowers: ['玫瑰', '满天星'], note: '蓝+白' }],
    caution: '可制干花；勤换水。',
    careSummary: '勿忘我；清洁水质，可倒挂制干花。',
    careTips: ['可制干花'],
    bloomNote: '约 7—10 天',
  }),
]

module.exports = {
  ...exportKind('配叶', FOLIAGE),
  ...exportKind('盆栽', POTTED),
  ...exportKind('洋牡丹', [SMALL[0]]),
  ...exportKind('银莲花', [SMALL[1]]),
  ...exportKind('翠珠', [SMALL[2]]),
  ...exportKind('蕾丝花', [SMALL[3]]),
  ...exportKind('紫罗兰', [SMALL[4]]),
  ...exportKind('勿忘我', [SMALL[5]]),
}
