const { exportKind } = require('./shared')

const SPECS = [
  {
    variety: '粉钻',
    alias: 'Pink Diamond',
    scientificName: "Dianthus 'Pink Diamond'",
    namingNote: '温柔粉色康乃馨代表，母亲节与感恩场景高频，瓣层繁密',
    color: '柔和粉色，瓣缘锯齿、层叠繁密，开放后仍较饱满',
    scent: '淡香',
    featureRefs: ['trait.soft_pink', 'trait.thick_petal'],
    distinguishFrom: [
      { name: '马斯特', difference: '正红经典，而非柔粉' },
      { name: '野马', difference: '复古紫调，更特别' },
      { name: '粉钻', difference: '柔粉、瓣多、耐插，是粉色康乃馨最常见辨识' },
    ],
    meaning: '感恩、温柔与「很体贴的粉色祝福」',
    paragraphs: [
      '粉钻的柔粉不像玫瑰那样直白——它更适合母亲节、感谢老师、探望女性长辈：热烈里带着体贴，不会过于张扬。',
      '与红、白康乃馨混搭是花店经典组合；单品种粉钻也适合日常家居，配绿康或尤加利即可。',
    ],
    occasions: ['母亲节', '教师节', '感恩', '探望', '日常家居'],
    colorLabel: '柔粉',
    colorMeaning: '感恩、温柔、体贴',
    pairing: [
      { style: '母亲节', flowers: ['马斯特', '白雪公主'], note: '红粉白康乃馨' },
      { style: '日常温柔', flowers: ['洋桔梗', '翠珠'], note: '粉白轻盈' },
    ],
    caution: '撕去茎节叶片，避免花瓣沾水；远离成熟水果（乙烯）。',
    careSummary: '粉钻瓣层多、耐插；撕去关节处叶片，勤换水，避免花瓣沾水。',
    careTips: ['撕去关节处叶片，减少腐烂', '远离热源与成熟水果'],
    bloomNote: '粉色康乃馨，勤换水可稳定保持 7—14 天',
  },
  {
    variety: '野马',
    alias: 'Mustang',
    scientificName: "Dianthus 'Mustang'",
    namingNote: '复古紫色康乃馨，辨识度高于常规红粉白',
    color: '低饱和复古紫，瓣缘锯齿，色调偏莫兰迪',
    scent: '淡香',
    featureRefs: ['trait.muted_retro', 'trait.soft_pink'],
    distinguishFrom: [
      { name: '粉钻', difference: '柔粉，而非复古紫' },
      { name: '马斯特', difference: '正红，而非紫色系' },
      { name: '野马', difference: '复古紫、特别、耐插，是紫色康乃馨代表' },
    ],
    meaning: '独特、复古与「不走寻常路的关心」',
    paragraphs: [
      '野马的紫不是艳俗的紫——它带一点灰、一点旧，适合送给审美偏成熟、喜欢低调特别的人。',
      '与尤加利、银叶类同插很有森系质感；表白场景不如玫瑰，但纪念日、感谢、送同事都很得体。',
    ],
    occasions: ['纪念日', '感谢', '送同事', '家居装饰'],
    colorLabel: '复古紫',
    colorMeaning: '独特、成熟、低调',
    pairing: [
      { style: '森系', flowers: ['尤加利叶', '银芽柳'], note: '紫绿灰调' },
      { style: '特别感', flowers: ['洋牡丹', '翠珠'], note: '低饱和混搭' },
    ],
    caution: '复古色系对水质敏感，须勤换水；避免挤压花瓣。',
    careSummary: '野马为复古紫康乃馨；勤换水、撕去下部叶片，保持通风。',
    careTips: ['勤换水，水质变浑立即更换', '避免挤压层叠花瓣'],
    bloomNote: '复古紫康乃馨，耐插 7—14 天',
  },
  {
    variety: '白雪公主',
    alias: 'Snow White',
    scientificName: "Dianthus 'Snow White'",
    namingNote: '白色康乃馨代表，纯洁与感谢，教师节常见',
    color: '纯白，瓣层洁净，开放后仍保持较好轮廓',
    scent: '淡香',
    featureRefs: ['trait.pure_white', 'trait.thick_petal'],
    distinguishFrom: [
      { name: '马斯特', difference: '正红，而非纯白' },
      { name: '粉钻', difference: '柔粉，而非白色' },
      { name: '白雪公主', difference: '纯白、耐插，是白康乃馨最常见辨识' },
    ],
    meaning: '纯洁、感谢与「很干净的心意」',
    paragraphs: [
      '白雪公主的白康乃馨，适合教师节、感谢、探望——比百合更日常，比玫瑰更克制，表达「谢谢」非常准确。',
      '与红、粉康乃馨同插能做出层次；婚礼白绿系也常用，但需注意勿与易染花粉的花材混放。',
    ],
    occasions: ['教师节', '感谢', '探望', '婚礼配花'],
    colorLabel: '纯白',
    colorMeaning: '纯洁、感谢、真诚',
    pairing: [
      { style: '感谢花束', flowers: ['马斯特', '粉钻'], note: '红白粉组合' },
      { style: '婚礼白绿', flowers: ['绿康', '尤加利叶'], note: '洁净高级' },
    ],
    caution: '白色花瓣易显水质问题，须勤换水、洗净花瓶。',
    careSummary: '白雪公主为纯白康乃馨；勤换水、撕去茎节叶片，保持水质洁净。',
    careTips: ['白色花瓣对水质敏感，每日换水', '撕去关节处叶片'],
    bloomNote: '白色康乃馨，勤换水可稳定 7—14 天',
  },
  {
    variety: '多头康乃馨',
    alias: 'Spray Carnation',
    scientificName: "Dianthus 'Spray Carnation'",
    namingNote: '多朵同枝开放，花量大、性价比高，配花与家居常用',
    color: '多色可选，同一枝多朵小花开放，整体花量感强',
    scent: '淡香',
    featureRefs: ['trait.multi_head', 'trait.spray_huge'],
    flowerForm: ['trait.multi_head'],
    distinguishFrom: [
      { name: '单头康乃馨', difference: '单朵更大，而非多朵同枝' },
      { name: '满天星', difference: '细碎配花，而非康乃馨瓣形' },
      { name: '多头康乃馨', difference: '多朵同枝、性价比高，是配花高频选择' },
    ],
    meaning: '热闹、实惠与「把气氛撑起来」',
    paragraphs: [
      '多头康乃馨的价值在于花量——同一束里能看到很多朵小花依次开放，适合插满一瓶、做配花、或预算有限但想要「看起来很满」的场景。',
      '枯谢小头及时剪除，可延长整体观赏；与玫瑰、百合主花同插时，注意留足瓶口空间。',
    ],
    occasions: ['配花', '日常家居', '开业填充', '预算友好'],
    colorLabel: '多色',
    colorMeaning: '热闹、实惠、花量大',
    pairing: [
      { style: '满瓶家居', flowers: ['尤加利叶'], note: '单品种多色即可' },
      { style: '主花配搭', flowers: ['玫瑰', '百合'], note: '增加花量层次' },
    ],
    caution: '多头需预留瓶口空间；枯谢小头及时剪除。',
    careSummary: '多头康乃馨花量大；预留瓶口空间，枯谢小头及时剪除，勤换水。',
    careTips: ['枯谢小头及时剪除', '预留瓶口，避免拥挤闷湿'],
    bloomNote: '多头康乃馨，花量大，观赏期 7—14 天',
  },
  {
    variety: '绿色康乃馨',
    alias: 'Green',
    scientificName: "Dianthus 'Green'",
    namingNote: '绿色康乃馨，清新独特，婚庆与创意花束常见',
    color: '清新绿色，瓣缘锯齿，色调介于叶与花之间，辨识度高',
    scent: '淡香',
    featureRefs: ['trait.thick_petal'],
    distinguishFrom: [
      { name: '绿康', difference: '有时混称，以实际到货瓣形为准' },
      { name: '粉钻', difference: '柔粉，而非绿色' },
      { name: '绿色康乃馨', difference: '绿色调、独特、耐插，是创意花束常见选择' },
    ],
    meaning: '清新、独特与「打破常规的颜色」',
    paragraphs: [
      '绿色康乃馨不是「未开放」，而是刻意的绿色调——适合现代风、森系、开业与创意花束，和尤加利、白花、香槟色花材都很搭。',
      '收花人若第一次见可能会问「为什么是绿的」，正好可以成为话题；表达「特别、新鲜、不走寻常路」。',
    ],
    occasions: ['开业', '创意花束', '森系', '家居装饰'],
    colorLabel: '绿',
    colorMeaning: '清新、独特、新生',
    pairing: [
      { style: '森系开业', flowers: ['尤加利叶', '白雪山'], note: '绿白高级' },
      { style: '现代创意', flowers: ['香槟玫瑰', '翠珠'], note: '低饱和混搭' },
    ],
    caution: '绿色系对水质敏感，勤换水；避免挤压。',
    careSummary: '绿色康乃馨独特色调；勤换水、撕去茎节叶片，保持通风。',
    careTips: ['勤换水，保持水质清洁', '撕去关节处叶片'],
    bloomNote: '绿色康乃馨，耐插 7—14 天',
  },
]

module.exports = exportKind('康乃馨', SPECS)
