const { exportKind } = require('./shared')

const SPECS = [
  {
    variety: '花手鞠',
    alias: 'Hanatemari',
    scientificName: "Hydrangea 'Hanatemari'",
    namingNote: '重瓣大花绣球，花球极大，日式高级花束常见',
    color: '蓝或粉紫，重瓣层叠，花球直径大、轮廓圆润饱满',
    scent: '几乎无香',
    featureRefs: ['trait.spray_ball', 'trait.huge_flower'],
    distinguishFrom: [
      { name: '无尽夏', difference: '可调色单瓣感，而非重瓣大花球' },
      { name: '头花', difference: '花球中等，性价比路线' },
      { name: '花手鞠', difference: '重瓣、花球极大，是高端绣球代表' },
    ],
    meaning: '圆满、隆重与「一束就很满」',
    paragraphs: [
      '花手鞠的绣球不是点缀，而是主花——一个花球就能撑住整束的分量，适合婚礼、开业、高端庆典。',
      '吸水大是绣球共性，收到后建议十字剪或深水瓶养；喷雾保湿可延长观赏。',
    ],
    occasions: ['婚礼', '开业', '高端庆典', '家居主花'],
    colorLabel: '蓝/粉紫',
    colorMeaning: '圆满、隆重、高级感',
    pairing: [
      { style: '婚礼主花', flowers: ['白玫瑰', '尤加利叶'], note: '蓝白或粉白' },
      { style: '开业贺礼', flowers: ['绿康', '百合'], note: '大气满瓶' },
    ],
    caution: '吸水不足易萎蔫；可十字剪或烫茎急救。喷雾保湿。',
    careSummary: '花手鞠花球大、吸水多；深水瓶养，可喷雾保湿，茎部可十字剪。',
    careTips: ['吸水不足时可十字剪或烫茎', '每日喷雾保湿'],
    bloomNote: '重瓣大花绣球，需充足吸水',
  },
  {
    variety: '魔幻系列',
    alias: 'Magical',
    scientificName: "Hydrangea 'Magical'",
    namingNote: '复古色调、开放过程变色的绣球系列，艺术感强',
    color: '复古蓝紫或粉绿，开放过程中色调持续变化',
    scent: '几乎无香',
    featureRefs: ['trait.color_shift', 'trait.muted_retro', 'trait.spray_ball'],
    distinguishFrom: [
      { name: '无尽夏', difference: '更偏经典蓝粉，变色不如魔幻明显' },
      { name: '爆米花', difference: '瓣缘卷曲可爱，而非复古变色' },
      { name: '魔幻系列', difference: '复古变色、艺术感，是绣球特色系列' },
    ],
    meaning: '变化、艺术感与「时间会改变的美」',
    paragraphs: [
      '魔幻系列的魅力在于「会变」——收到时的颜色未必是三天后的颜色，适合喜欢观察花材变化、审美偏艺术的人。',
      '阴凉通风可减缓开放速度；与尤加利、银叶类同插，复古色调更完整。',
    ],
    occasions: ['家居观赏', '艺术花束', '纪念日', '拍照'],
    colorLabel: '复古多色',
    colorMeaning: '变化、艺术、独特',
    pairing: [
      { style: '复古森系', flowers: ['尤加利叶', '银芽柳'], note: '灰绿蓝紫' },
      { style: '家居主花', flowers: ['洋桔梗'], note: '单球即可' },
    ],
    caution: '色调变化属正常；避直射可减缓。须保持吸水。',
    careSummary: '魔幻系列开放过程色调变化；阴凉通风、充足吸水，可喷雾保湿。',
    careTips: ['开放后期色调变化属正常', '茎部可十字剪增加吸水'],
    bloomNote: '复古变色绣球，观赏期约 5—10 天',
  },
  {
    variety: '贝拉安娜',
    alias: 'Annabelle',
    scientificName: "Hydrangea paniculata 'Annabelle'",
    namingNote: '圆锥绣球切花，白绿色、野趣自然风代表',
    color: '白转绿，圆锥花序，线条比大花绣球更野趣',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white', 'trait.spray_ball'],
    distinguishFrom: [
      { name: '大花绣球', difference: '团状圆球，而非圆锥花序' },
      { name: '无尽夏', difference: '蓝粉可调色，而非白绿圆锥' },
      { name: '贝拉安娜', difference: '白绿圆锥、野趣，是自然风绣球代表' },
    ],
    meaning: '自然、野趣与「不刻意的美」',
    paragraphs: [
      '贝拉安娜更像从花园剪下来的——适合自然风、野趣、田园系花束，与雏菊、蕾丝花、尤加利极搭。',
      '白绿色调适合婚礼、日常家居；比蓝紫绣球更「轻」，不厚重。',
    ],
    occasions: ['自然风花束', '婚礼', '日常家居', '野趣'],
    colorLabel: '白/绿',
    colorMeaning: '自然、野趣、清新',
    pairing: [
      { style: '野趣', flowers: ['小雏菊', '蕾丝花'], note: '白绿轻盈' },
      { style: '婚礼', flowers: ['尤加利叶', '白玫瑰'], note: '自然高级' },
    ],
    caution: '圆锥花序易损，轻拿轻放；保持吸水。',
    careSummary: '贝拉安娜为圆锥绣球；勤换水，轻拿轻放，可喷雾保湿。',
    careTips: ['佛焰苞/花序易损，避免挤压', '勤换水保证吸水'],
    bloomNote: '圆锥绣球，野趣自然风',
  },
  {
    variety: '爆米花',
    alias: 'Popcorn',
    scientificName: "Hydrangea 'Popcorn'",
    namingNote: '瓣缘卷曲如爆米花，可爱系绣球代表',
    color: '蓝或粉，小瓣卷曲密集，整体轮廓像爆米花',
    scent: '几乎无香',
    featureRefs: ['trait.spray_ball'],
    distinguishFrom: [
      { name: '花手鞠', difference: '重瓣大花，而非卷曲小瓣' },
      { name: '头花', difference: '标准团状，瓣缘不卷曲' },
      { name: '爆米花', difference: '卷曲小瓣、可爱，辨识度高' },
    ],
    meaning: '可爱、治愈与「让人想拍照」',
    paragraphs: [
      '爆米花的名字很准——瓣缘卷曲、密集、圆滚滚，适合送年轻人、做家居点缀、或想要「可爱而不是隆重」的绣球场景。',
      '与满天星、小菊同插，整束会更「甜」；单球插瓶也足够有趣。',
    ],
    occasions: ['送朋友', '家居', '拍照', '生日'],
    colorLabel: '蓝/粉',
    colorMeaning: '可爱、治愈、轻松',
    pairing: [
      { style: '可爱风', flowers: ['满天星', '小雏菊'], note: '蓝粉白' },
      { style: '单球家居', flowers: ['尤加利叶'], note: '简约即可' },
    ],
    caution: '保持吸水；卷曲瓣缝易闷湿，须通风。',
    careSummary: '爆米花绣球瓣缘卷曲；充足吸水，保持通风，可喷雾。',
    careTips: ['茎部十字剪增加吸水', '通风防闷湿'],
    bloomNote: '可爱系卷曲绣球',
  },
  {
    variety: '头花',
    alias: 'Head Flower',
    scientificName: "Hydrangea 'Head Flower'",
    namingNote: '中等花球绣球，性价比高，日常与开业常见',
    color: '蓝或粉，团状花球中等大小，轮廓标准',
    scent: '几乎无香',
    featureRefs: ['trait.spray_ball'],
    distinguishFrom: [
      { name: '花手鞠', difference: '花球更大、重瓣' },
      { name: '无尽夏', difference: '品牌系列，色调与球感略异' },
      { name: '头花', difference: '中等花球、性价比高，是日常绣球常见选择' },
    ],
    meaning: '实惠、圆满与「日常也买得起的主花」',
    paragraphs: [
      '头花是绣球里的「实用款」——花球够看、价格通常比花手鞠友好，适合日常家居、开业、探望想要「有一球绣球」的场景。',
      '养护要点仍是吸水：深水瓶、十字剪、勤换水，比大多数花材更依赖水分。',
    ],
    occasions: ['日常家居', '开业', '探望', '预算友好'],
    colorLabel: '蓝/粉',
    colorMeaning: '圆满、实惠、日常',
    pairing: [
      { style: '日常', flowers: ['绿康', '百合'], note: '蓝绿白' },
      { style: '开业', flowers: ['向日葵', '尤加利叶'], note: '明亮满瓶' },
    ],
    caution: '绣球吸水大；缺水易萎蔫，须勤换水。',
    careSummary: '头花绣球中等花球；深水瓶养，勤换水，茎部可十字剪。',
    careTips: ['吸水不足时十字剪或烫茎', '每日换水'],
    bloomNote: '性价比绣球，需充足吸水',
  },
]

module.exports = exportKind('绣球', SPECS)
