const { exportKind } = require('./shared')

const SPECS = [
  {
    variety: '落日珊瑚',
    alias: 'Coral Sunset',
    scientificName: "Paeonia 'Coral Sunset'",
    namingNote: '珊瑚色开放后转奶油色，芍药变色系列代表',
    color: '初开珊瑚橙，随后渐转奶油黄，层次随时间变化',
    scent: '浓香，甜美',
    featureRefs: ['trait.color_shift', 'trait.gradient_warm', 'trait.huge_flower'],
    distinguishFrom: [
      { name: '莎拉', difference: '柔粉重瓣，色调稳定' },
      { name: '红富士', difference: '正红，而非珊瑚变色' },
      { name: '落日珊瑚', difference: '珊瑚→奶油变色，是芍药高级感代表' },
    ],
    meaning: '短暂而盛美、时间与「值得等待的开放」',
    paragraphs: [
      '落日珊瑚最美的是过程——收到时偏橙，开放后渐转奶油，像把日落留在花瓶里。适合懂花、愿意观察变化的人。',
      '芍药瓶插期短是常态，选微开入瓶、浅水阴凉，可稳定几天高光时刻；与莎拉、奶油碗同插，色调层次极丰富。',
    ],
    occasions: ['婚礼', '纪念日', '家居观赏', '高端赠礼'],
    colorLabel: '珊瑚→奶油',
    colorMeaning: '时间、变化、盛美',
    pairing: [
      { style: '婚礼芍药', flowers: ['莎拉', '奶油碗'], note: '粉珊瑚白层次' },
      { style: '单品种观赏', flowers: ['尤加利叶'], note: '突出变色' },
    ],
    caution: '瓶插期短；开放变色属正常。浅水、避直射。',
    careSummary: '落日珊瑚开放过程色调变化；浅水养护，阴凉通风，选微开入瓶。',
    careTips: ['开放后期色调变化属正常', '浅水养护，避免高温'],
    bloomNote: '变色芍药，观赏期约 3—5 天',
  },
  {
    variety: '奶油碗',
    alias: 'Bowl of Cream',
    scientificName: "Paeonia 'Bowl of Cream'",
    namingNote: '重瓣乳白芍药，圆润如碗，婚礼白系常见',
    color: '乳白重瓣，层叠圆润，开放后如奶油碗般饱满',
    scent: '浓香',
    featureRefs: ['trait.huge_flower', 'trait.pure_white'],
    distinguishFrom: [
      { name: '莎拉', difference: '柔粉，而非乳白' },
      { name: '杨妃出浴', difference: '粉白渐变，而非纯乳白' },
      { name: '奶油碗', difference: '乳白重瓣、圆润，是白芍药代表' },
    ],
    meaning: '温柔、圆满与「很柔软的重瓣美」',
    paragraphs: [
      '奶油碗的名字很贴切——重瓣、乳白、圆润，适合婚礼、纪念日、以及一切需要「柔软但隆重」的白。',
      '芍药花头重，需高瓶支撑；与莎拉、尤加利同插，是经典婚礼芍药组合。',
    ],
    occasions: ['婚礼', '纪念日', '家居', '高端赠礼'],
    colorLabel: '乳白',
    colorMeaning: '温柔、圆满、纯净',
    pairing: [
      { style: '婚礼白', flowers: ['莎拉', '尤加利叶'], note: '粉白绿' },
      { style: '家居', flowers: ['翠珠'], note: '乳白轻盈' },
    ],
    caution: '花头重易下垂；浅水、高瓶。瓶插期短。',
    careSummary: '奶油碗重瓣乳白；高瓶支撑，浅水养护，阴凉通风。',
    careTips: ['花头重，需高瓶支撑', '选微开入瓶'],
    bloomNote: '重瓣白芍药，约 3—5 天',
  },
  {
    variety: '红富士',
    alias: 'Red Charm',
    scientificName: "Paeonia 'Red Charm'",
    namingNote: '正红重瓣芍药，喜庆场合常见',
    color: '正红重瓣，层叠繁密，色调饱和',
    scent: '浓香',
    featureRefs: ['trait.classic_red', 'trait.huge_flower'],
    distinguishFrom: [
      { name: '落日珊瑚', difference: '珊瑚变色，而非正红' },
      { name: '莎拉', difference: '柔粉，而非正红' },
      { name: '红富士', difference: '正红重瓣，是喜庆芍药代表' },
    ],
    meaning: '热烈、喜庆与「很东方的红」',
    paragraphs: [
      '红富士的正红很适合春节、贺寿、开业——有牡丹的隆重感，但瓶插更「当下」，是中式喜庆花束常用芍药。',
      '与黄色、白色芍药或配花同插，可压住浓香的视觉重量；收到后尽快插瓶，微开状态最佳。',
    ],
    occasions: ['春节', '贺寿', '开业', '庆典'],
    colorLabel: '正红',
    colorMeaning: '喜庆、热烈、祝福',
    pairing: [
      { style: '喜庆', flowers: ['黄天霸', '绿康'], note: '红黄金绿' },
      { style: '庆典', flowers: ['莎拉', '尤加利叶'], note: '红粉层次' },
    ],
    caution: '浓香；瓶插期短。高瓶支撑重瓣花头。',
    careSummary: '红富士正红重瓣；高瓶支撑，浅水阴凉，选微开入瓶。',
    careTips: ['花头重，需高瓶', '浅水养护'],
    bloomNote: '正红重瓣芍药，约 3—5 天',
  },
  {
    variety: '杨妃出浴',
    alias: 'Yang Fei',
    scientificName: "Paeonia 'Yang Fei'",
    namingNote: '粉白渐变芍药，中式古典名，层次柔美',
    color: '外瓣粉、内瓣渐白，开放后层次如「出浴」般柔美',
    scent: '浓香',
    featureRefs: ['trait.soft_pink', 'trait.huge_flower', 'trait.gradient_warm'],
    distinguishFrom: [
      { name: '莎拉', difference: '整体柔粉，而非粉白渐变' },
      { name: '奶油碗', difference: '乳白为主，而非粉白' },
      { name: '杨妃出浴', difference: '粉白渐变、古典，是中式芍药代表' },
    ],
    meaning: '古典、柔美与「有故事感的粉白」',
    paragraphs: [
      '杨妃出浴的粉白渐变，适合送给喜欢中式审美、文学意象的人——名字本身就有画面感，不必解释太多。',
      '与莎拉、蕾丝花同插，婚礼与家居都成立；芍药季短暂，收到即珍惜。',
    ],
    occasions: ['婚礼', '纪念日', '探望', '家居'],
    colorLabel: '粉白渐变',
    colorMeaning: '古典、柔美、诗意',
    pairing: [
      { style: '中式婚礼', flowers: ['莎拉', '蕾丝花'], note: '粉白轻' },
      { style: '家居', flowers: ['尤加利叶'], note: '单品种即可' },
    ],
    caution: '瓶插期短；粉白瓣易损，轻拿轻放。',
    careSummary: '杨妃出浴粉白渐变；浅水、高瓶、阴凉，轻拿轻放。',
    careTips: ['轻拿轻放，避免挤压重瓣', '选微开入瓶'],
    bloomNote: '粉白渐变芍药，约 3—5 天',
  },
  {
    variety: '芭茨拉',
    alias: 'Bartzella',
    scientificName: "Paeonia 'Bartzella'",
    namingNote: '黄色交谊芍药，花型大、色调明亮，相对少见',
    color: '明亮黄色重瓣，层叠饱满，开放后花径大',
    scent: '淡香至中等',
    featureRefs: ['trait.yellow_gold', 'trait.huge_flower'],
    distinguishFrom: [
      { name: '落日珊瑚', difference: '珊瑚变色，而非正黄' },
      { name: '红富士', difference: '正红，而非黄色' },
      { name: '芭茨拉', difference: '明亮黄色、花大，是黄芍药代表' },
    ],
    meaning: '明亮、稀有与「芍药里的阳光」',
    paragraphs: [
      '黄色芍药并不常见——芭茨拉适合想要「芍药但不想粉红白」的场合，开业、生日、送长辈都很明亮。',
      '与白色、绿色配花同插，黄色主花会更高级；注意高瓶支撑与浅水养护。',
    ],
    occasions: ['开业', '生日', '贺寿', '家居'],
    colorLabel: '明黄',
    colorMeaning: '明亮、祝福、稀有',
    pairing: [
      { style: '明亮庆典', flowers: ['绿康', '白玫瑰'], note: '黄白绿' },
      { style: '家居', flowers: ['尤加利叶'], note: '单品种即可' },
    ],
    caution: '花头重；瓶插期短。高瓶支撑。',
    careSummary: '芭茨拉黄色重瓣；高瓶支撑，浅水阴凉，勤换水。',
    careTips: ['高瓶支撑大花头', '浅水养护'],
    bloomNote: '黄色芍药，约 3—5 天',
  },
]

module.exports = exportKind('芍药', SPECS)
