const { exportKind } = require('./shared')

const SPECS = [
  {
    variety: '阿波罗',
    alias: 'Apeldoorn',
    scientificName: "Tulipa 'Apeldoorn'",
    namingNote: '经典橙色单瓣郁金香，高脚杯形，春日高频',
    color: '明亮橙色，杯形线条挺拔，单朵辨识度高',
    scent: '几乎无香或极淡',
    featureRefs: ['trait.cup_trumpet', 'trait.yellow_gold'],
    flowerForm: ['trait.cup_trumpet'],
    distinguishFrom: [
      { name: '纯金', difference: '偏金黄，而非橙' },
      { name: '王朝', difference: '正红，而非橙' },
      { name: '阿波罗', difference: '橙色高脚杯，是经典橙郁金香代表' },
    ],
    meaning: '活力、春日与「很标准的橙色郁金香」',
    paragraphs: [
      '阿波罗的橙，比红郁金香更暖、比黄更跳——适合春日、生日、以及想要「一眼是郁金香」的明亮场景。',
      '郁金香花茎会继续生长，瓶口勿过窄；与纯金、白梦同插，荷兰田园感立刻出来。',
    ],
    occasions: ['春日', '生日', '家居', '赠礼'],
    colorLabel: '橙',
    colorMeaning: '活力、温暖、春日',
    pairing: [
      { style: '荷兰春日', flowers: ['纯金', '白梦'], note: '橙黄白' },
      { style: '单品种', flowers: ['尤加利叶'], note: '简约即可' },
    ],
    caution: '喜冷凉；远离暖气。花茎会继续生长，可每日微调。',
    careSummary: '阿波罗橙色郁金香；浅水养护，喜冷凉，花茎会继续生长可每日修剪。',
    careTips: ['花茎会继续伸长，可每日修剪高度', '避免与成熟水果同放'],
    bloomNote: '橙色高脚杯郁金香，约 5—7 天',
  },
  {
    variety: '纯金',
    alias: 'Strong Gold',
    scientificName: "Tulipa 'Strong Gold'",
    namingNote: '金黄色单瓣郁金香，明亮喜庆',
    color: '金黄色，杯形，色调均匀明亮',
    scent: '几乎无香',
    featureRefs: ['trait.yellow_gold', 'trait.cup_trumpet'],
    flowerForm: ['trait.cup_trumpet'],
    distinguishFrom: [
      { name: '阿波罗', difference: '橙色，而非金黄' },
      { name: '王朝', difference: '正红，而非黄' },
      { name: '纯金', difference: '金黄色、明亮，是黄郁金香代表' },
    ],
    meaning: '明亮、祝福与「春日里的金币」',
    paragraphs: [
      '纯金的黄很适合开业、生日、探望——比玫瑰更「春」，比菊花更「干净」，是一束里很提气的颜色。',
      '浅水、冷凉、远离暖气，是郁金香共通要点；与橙、白郁金香混搭极经典。',
    ],
    occasions: ['开业', '生日', '春日', '探望'],
    colorLabel: '金黄',
    colorMeaning: '明亮、祝福、财富感',
    pairing: [
      { style: '春日组合', flowers: ['阿波罗', '白梦'], note: '橙黄白' },
      { style: '开业', flowers: ['绿康'], note: '黄绿简洁' },
    ],
    caution: '远离暖气；花茎生长需预留瓶高。',
    careSummary: '纯金黄色郁金香；浅水、冷凉环境，花茎继续生长可微调。',
    careTips: ['浅水养护', '远离暖气与直射'],
    bloomNote: '金黄色郁金香，约 5—7 天',
  },
  {
    variety: '白梦',
    alias: 'White Dream',
    scientificName: "Tulipa 'White Dream'",
    namingNote: '白色单瓣郁金香，洁净婚礼与春日常用',
    color: '纯白，杯形线条干净，开放后优雅',
    scent: '几乎无香',
    featureRefs: ['trait.pure_white', 'trait.cup_trumpet'],
    flowerForm: ['trait.cup_trumpet'],
    distinguishFrom: [
      { name: '夜皇后', difference: '深紫近黑，而非白' },
      { name: '王朝', difference: '正红，而非白' },
      { name: '白梦', difference: '纯白高脚杯，是白郁金香代表' },
    ],
    meaning: '纯洁、春日与「很干净的一束白」',
    paragraphs: [
      '白梦的纯白适合婚礼、日常家居、以及任何需要「白但不想用玫瑰」的郁金香场景——线条比百合更几何。',
      '与黄、橙、红郁金香同插，是经典荷兰色盘；单品种白郁金香也足够高级。',
    ],
    occasions: ['婚礼', '春日', '日常家居', '赠礼'],
    colorLabel: '纯白',
    colorMeaning: '纯洁、清新、简约',
    pairing: [
      { style: '婚礼白', flowers: ['尤加利叶', '翠珠'], note: '白绿' },
      { style: '荷兰色盘', flowers: ['王朝', '纯金'], note: '红白黄' },
    ],
    caution: '喜冷凉；白瓣对水质敏感，勤换水。',
    careSummary: '白梦纯白郁金香；浅水、冷凉，勤换水保持洁净。',
    careTips: ['勤换水', '花茎继续生长可修剪'],
    bloomNote: '白色郁金香，约 5—7 天',
  },
  {
    variety: '夜皇后',
    alias: 'Queen of Night',
    scientificName: "Tulipa 'Queen of Night'",
    namingNote: '深紫近黑单瓣郁金香，神秘系代表',
    color: '深紫近黑，杯形，色调神秘而饱和',
    scent: '几乎无香',
    featureRefs: ['trait.cup_trumpet', 'trait.muted_retro'],
    flowerForm: ['trait.cup_trumpet'],
    distinguishFrom: [
      { name: '王朝', difference: '正红，而非深紫' },
      { name: '白梦', difference: '纯白，而非深紫' },
      { name: '夜皇后', difference: '深紫近黑，是神秘系郁金香代表' },
    ],
    meaning: '神秘、个性与「郁金香里的暗夜」',
    paragraphs: [
      '夜皇后适合送给审美偏酷、喜欢深色花材的人——它不是「丧」，而是神秘与高级，和银叶、尤加利极搭。',
      '与白色、黄色郁金香对比搭配，视觉冲击力很强；单品种插瓶也足够有态度。',
    ],
    occasions: ['纪念日', '个性赠礼', '家居', '拍照'],
    colorLabel: '深紫近黑',
    colorMeaning: '神秘、个性、高级',
    pairing: [
      { style: '对比', flowers: ['白梦', '纯金'], note: '黑白黄' },
      { style: '酷感', flowers: ['银芽柳', '尤加利叶'], note: '深色系' },
    ],
    caution: '喜冷凉；远离暖气。浅水养护。',
    careSummary: '夜皇后深紫郁金香；浅水、冷凉、避暖气，花茎可每日微调。',
    careTips: ['远离暖气', '浅水养护'],
    bloomNote: '深紫郁金香，约 5—7 天',
  },
  {
    variety: '鹦鹉系列',
    alias: 'Parrot Tulip',
    scientificName: "Tulipa 'Parrot Tulip'",
    namingNote: '卷瓣鹦鹉郁金香，边缘不规则，艺术感强',
    color: '多色，瓣缘卷曲如鹦鹉羽，轮廓独特',
    scent: '几乎无香',
    featureRefs: ['trait.recurved_petal', 'trait.cup_trumpet'],
    flowerForm: ['trait.recurved_petal'],
    distinguishFrom: [
      { name: '单瓣系列', difference: '杯形规整，而非卷瓣' },
      { name: '重瓣系列', difference: '层叠重瓣，而非羽状卷边' },
      { name: '鹦鹉系列', difference: '卷瓣羽状、艺术感，是郁金香特色系列' },
    ],
    meaning: '艺术、个性与「不像「标准」的郁金香」',
    paragraphs: [
      '鹦鹉系列适合拍照、艺术花束、以及收花人已经见过普通郁金香、想要「特别一点」的场景——瓣缘的卷曲是最大辨识度。',
      '卷瓣结构略娇气，避免挤压与高温；与单瓣郁金香混搭，同一束里会有节奏变化。',
    ],
    occasions: ['拍照', '艺术花束', '纪念日', '家居'],
    colorLabel: '多色',
    colorMeaning: '艺术、个性、独特',
    pairing: [
      { style: '艺术混搭', flowers: ['王朝', '白梦'], note: '卷瓣+杯形' },
      { style: '单品种', flowers: ['尤加利叶'], note: '突出卷瓣' },
    ],
    caution: '卷瓣易损；喜冷凉，避暖气。',
    careSummary: '鹦鹉郁金香卷瓣；浅水冷凉，轻拿轻放，避免挤压卷瓣。',
    careTips: ['轻拿轻放', '远离暖气'],
    bloomNote: '卷瓣鹦鹉郁金香，约 5—7 天',
  },
  {
    variety: '重瓣系列',
    alias: 'Double Tulip',
    scientificName: "Tulipa 'Double Tulip'",
    namingNote: '重瓣郁金香，层叠如牡丹，春日高端',
    color: '多色，重瓣层叠，开放后饱满',
    scent: '几乎无香',
    featureRefs: ['trait.huge_flower', 'trait.cup_trumpet'],
    distinguishFrom: [
      { name: '单瓣系列', difference: '单杯形，而非重瓣' },
      { name: '鹦鹉系列', difference: '卷边羽状，而非层叠重瓣' },
      { name: '重瓣系列', difference: '层叠饱满，是高端郁金香代表' },
    ],
    meaning: '隆重、春日与「郁金香里的牡丹感」',
    paragraphs: [
      '重瓣郁金香开放后像「郁金香里的牡丹」——适合纪念日、高端赠礼，以及想要郁金香但希望更饱满的场景。',
      '花头较重，瓶口留足空间；与单瓣郁金香同插，同一束里会有大小节奏。',
    ],
    occasions: ['纪念日', '高端赠礼', '春日', '婚礼'],
    colorLabel: '多色',
    colorMeaning: '隆重、饱满、春日',
    pairing: [
      { style: '高端', flowers: ['白梦', '王朝'], note: '重瓣+单瓣' },
      { style: '婚礼', flowers: ['尤加利叶'], note: '单品种即可' },
    ],
    caution: '重瓣易闷湿；通风、浅水、冷凉。',
    careSummary: '重瓣郁金香层叠饱满；浅水冷凉，通风，轻拿轻放。',
    careTips: ['通风防闷湿', '花茎生长可修剪'],
    bloomNote: '重瓣郁金香，约 5—7 天',
  },
]

module.exports = exportKind('郁金香', SPECS)
