export default defineAppConfig({
  lazyCodeLoading: 'requiredComponents',
  pages: [
    'pages/login/index',
    'pages/home/index',
    'pages/category/index',
    'pages/wiki/index',
    'pages/cart/index',
    'pages/mine/index',
    'pages/invite/staff/index',
    'pages/invite/join/index',
  ],
  subPackages: [
    {
      root: 'pagesCustomer',
      pages: [
        'goods/detail',
        'goods/list',
        'search/index',
        'customize/index',
        'customize/pick',
        'customize/preview',
        'order/confirm',
        'order/list',
        'order/detail',
        'member/index',
        'member/points',
        'member/level',
        'member/signin',
        'address/list',
        'address/edit',
        'profile/edit',
        'favorite/index',
        'feedback/index',
        'other/index',
        'wiki/detail',
      ],
    },
    {
      root: 'pagesMerchant',
      pages: [
        'dashboard/index',
        'order/list',
        'order/detail',
        'goods/list',
        'goods/edit',
        'goods/stock-in',
        'goods/stock-in-import',
        'goods/stock-out',
        'goods/warehouse-history',
        'category/list',
        'category/edit',
        'flower/picker',
        'verify/index',
        'staff/index',
        'staff/detail',
        'shop/setting',
        'shop/sales-strategy/index',
        'shop/sales-strategy/edit',
        'shop/goods-picker',
        'asset/index',
        'wiki/index',
        'wiki/edit',
        'wiki/care-reference',
      ],
    },
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '梵宇花店',
    navigationBarTextStyle: 'black',
    navigationStyle: 'custom',
  },
  permission: {
    'scope.userLocation': {
      desc: '你的位置信息将用于地图选择收货地址',
    },
  },
  requiredPrivateInfos: ['chooseAddress', 'chooseLocation', 'getLocation'],
  tabBar: {
    color: '#999',
    selectedColor: '#e53935',
    backgroundColor: '#fff',
    borderStyle: 'black',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'images/tab/home.png',
        selectedIconPath: 'images/tab/home-active.png',
      },
      {
        pagePath: 'pages/category/index',
        text: '商城',
        iconPath: 'images/tab/category.png',
        selectedIconPath: 'images/tab/category-active.png',
      },
      {
        pagePath: 'pages/wiki/index',
        text: '百科',
        iconPath: 'images/tab/wiki.png',
        selectedIconPath: 'images/tab/wiki-active.png',
      },
      {
        pagePath: 'pages/cart/index',
        text: '购物车',
        iconPath: 'images/tab/cart.png',
        selectedIconPath: 'images/tab/cart-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'images/tab/mine.png',
        selectedIconPath: 'images/tab/mine-active.png',
      },
    ],
  },
})
